name: DevTech Auto News

on:
  schedule:
    - cron: "0 */8 * * *"  
  workflow_dispatch:   

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run news fetch
        run: npm start

      - name: Commit & push multiple commits
        run: |
          git config user.name "Derrick-MUGISHA"
          git config user.email "derrickmugisha169@gmail.com"
          # Loop through each article file created by the script
          for f in data/article_*.md
          do
            git add "$f"
            git commit -m "Auto news update: $(date -u) - $(basename $f)"
          done
          git push
